development:
  SMTP_USER_EMAIL: ""
  SMTP_USER_PASSWORD: ""
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""

test:
  SMTP_USER_EMAIL: ""
  SMTP_USER_PASSWORD: ""
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""

production:
  SMTP_USER_EMAIL: ""
  SMTP_USER_PASSWORD: ""
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""